# Generated by Django 2.2.2 on 2020-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_category_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category_interest',
            field=models.CharField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS')], default='GAMES', max_length=20),
        ),
    ]
