# Generated by Django 2.2.2 on 2020-08-21 00:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200819_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category_interest',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], default='news', max_length=71),
        ),
    ]
