# Generated by Django 2.2.2 on 2020-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_score',
            field=models.IntegerField(default=0),
        ),
    ]
