# Generated by Django 2.2.2 on 2020-08-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200821_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bad_words',
            field=models.IntegerField(default=0),
        ),
    ]
