# Generated by Django 2.2.2 on 2020-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_category_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='category_interest',
        ),
        migrations.AddField(
            model_name='account',
            name='primary_interest',
            field=models.CharField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], default='NEWS', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='secondary_interest',
            field=models.CharField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], default='NEWS', max_length=20),
        ),
    ]
