# Generated by Django 2.2.2 on 2020-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200819_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='primary_interest',
            field=models.CharField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], default='LEISURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='secondary_interest',
            field=models.CharField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], default='AUTOMOTIVE', max_length=20),
        ),
    ]
