# Generated by Django 2.2.2 on 2020-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200819_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='primary_interest',
        ),
        migrations.RemoveField(
            model_name='account',
            name='secondary_interest',
        ),
        migrations.AddField(
            model_name='account',
            name='interests',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
