# Generated by Django 2.2.2 on 2020-08-20 15:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200820_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], max_length=71),
        ),
    ]
