# Generated by Django 2.2.2 on 2020-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200820_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interests',
            field=models.CharField(choices=[('games', 'GAMES'), ('social', 'SOCIAL'), ('music', 'MUSIC'), ('news', 'NEWS'), ('finance', 'FINANCE'), ('movies', 'MOVIES'), ('sports', 'SPORTS'), ('travel', 'TRAVEL'), ('automotive', 'AUTOMOTIVE'), ('leisure', 'LEISURE')], default='news', max_length=20),
        ),
    ]
